/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	ingressgroupv1 "k8s.io/ingress-nginx/pkg/apis/ingressgroup/v1"
)

// FakeIngressGroups implements IngressGroupInterface
type FakeIngressGroups struct {
	Fake *FakeCrV1
	ns   string
}

var ingressgroupsResource = schema.GroupVersionResource{Group: "cr.example.apiextensions.k8s.io", Version: "v1", Resource: "ingressgroups"}

var ingressgroupsKind = schema.GroupVersionKind{Group: "cr.example.apiextensions.k8s.io", Version: "v1", Kind: "IngressGroup"}

// Get takes name of the ingressGroup, and returns the corresponding ingressGroup object, and an error if there is any.
func (c *FakeIngressGroups) Get(name string, options v1.GetOptions) (result *ingressgroupv1.IngressGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ingressgroupsResource, c.ns, name), &ingressgroupv1.IngressGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ingressgroupv1.IngressGroup), err
}

// List takes label and field selectors, and returns the list of IngressGroups that match those selectors.
func (c *FakeIngressGroups) List(opts v1.ListOptions) (result *ingressgroupv1.IngressGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ingressgroupsResource, ingressgroupsKind, c.ns, opts), &ingressgroupv1.IngressGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &ingressgroupv1.IngressGroupList{ListMeta: obj.(*ingressgroupv1.IngressGroupList).ListMeta}
	for _, item := range obj.(*ingressgroupv1.IngressGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ingressGroups.
func (c *FakeIngressGroups) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ingressgroupsResource, c.ns, opts))

}

// Create takes the representation of a ingressGroup and creates it.  Returns the server's representation of the ingressGroup, and an error, if there is any.
func (c *FakeIngressGroups) Create(ingressGroup *ingressgroupv1.IngressGroup) (result *ingressgroupv1.IngressGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ingressgroupsResource, c.ns, ingressGroup), &ingressgroupv1.IngressGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ingressgroupv1.IngressGroup), err
}

// Update takes the representation of a ingressGroup and updates it. Returns the server's representation of the ingressGroup, and an error, if there is any.
func (c *FakeIngressGroups) Update(ingressGroup *ingressgroupv1.IngressGroup) (result *ingressgroupv1.IngressGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ingressgroupsResource, c.ns, ingressGroup), &ingressgroupv1.IngressGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ingressgroupv1.IngressGroup), err
}

// Delete takes name of the ingressGroup and deletes it. Returns an error if one occurs.
func (c *FakeIngressGroups) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(ingressgroupsResource, c.ns, name), &ingressgroupv1.IngressGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIngressGroups) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ingressgroupsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &ingressgroupv1.IngressGroupList{})
	return err
}

// Patch applies the patch and returns the patched ingressGroup.
func (c *FakeIngressGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *ingressgroupv1.IngressGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ingressgroupsResource, c.ns, name, pt, data, subresources...), &ingressgroupv1.IngressGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ingressgroupv1.IngressGroup), err
}
